=== eudi-implementation/dc4eu-vc-minmod/standards/schema_ehic.json
{
    "$id": "ehic_v0",
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "type": "object",
    "properties": {
        "subject": {
            "type": "object",
            "properties": {
                "forename": {
                    "type": "string"
                },
                "family_name": {
                    "type": "string"
                },
                "date_of_birth": {
                    "type": "string",
                    "format": "date"
                }
            },
            "required": [
                "forename",
                "family_name",
                "date_of_birth"
            ]
        },
        "social_security_pin": {
            "type": "string",
            "description": "Personal Identification Number as defined in the issuing institution"
        },
        "period_entitlement": {
            "type": "object",
            "properties": {
                "starting_date": {
                    "type": "string",
                    "format": "date"
                },
                "ending_date": {
                    "type": "string",
                    "format": "date"
                }
            },
            "required": [
                "starting_date",
                "ending_date"
            ]
        },
        "document_id": {
            "type": "string",
            "pattern": "^[-a-zA-Z0-9]{1,65}$"
        },
        "competent_institution": {
            "type": "object",
            "properties": {
                "institution_id": {
                    "$ref": "#/$defs/eessi_institution_id"
                },
                "institution_name": {
                    "type": "string"
                },
                "institution_country": {
                    "$ref": "#/$defs/iso3166_1_eu_efta_country_code"
                }
            },
            "required": [
                "institution_id",
                "institution_country"
            ]
        }
    },
    "required": [
        "social_security_pin",
        "period_entitlement",
        "document_id",
        "competent_institution"
    ],
    "$defs": {
        "iso3166_1_eu_efta_country_code": {
            "type": "string",
            "pattern": "^(AT|BE|BG|HR|CY|CZ|DK|EE|FI|FR|DE|EL|HU|IS|IE|IT|LV|LI|LT|LU|MT|NL|NO|PL|PT|RO|SK|SI|ES|SE|CH|UK|EU){1}$",
            "description": "Country code according to EU/EFTA-Countries according to ISO-3166-1 + UK"
        },
        "eessi_institution_id": {
            "type": "string",
            "pattern": "^(AT|BE|BG|HR|CY|CZ|DK|EE|FI|FR|DE|EL|HU|IS|IE|IT|LV|LI|LT|LU|MT|NL|NO|PL|PT|RO|SK|SI|ES|SE|CH|UK|EU):[a-zA-Z0-9]{4,10}$",
            "description": "Institution ID in the format 'AT:19789'"
        }
    }
}

=== eudi-implementation/dc4eu-vc-minmod/standards/ehic.json
{
    "subject": {
        "forename": "Magnus",
        "family_name": "Svensson",
        "date_of_birth": "1986-02-23",
        "other_elements": {
            "sex": "01",
            "forename_at_birth": "Magnus",
            "family_name_at_birth": "Svensson"
        }
    },
    "social_security_pin": "1234",
    "period_entitlement": {
        "starting_date": "1970-01-01",
        "ending_date": "2038-01-19"
    },
    "document_id": "12354",
    "competent_institution": {
        "institution_id": "SE:1234",
        "institution_name": "Myndigheten",
        "institution_country": "SE"
    }
}
